### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by harishkotra** [ElasticEmail/ElasticEmail.Wordpress-EmailSend#1]
My error log is filled with the following message: 

`PHP Fatal error:  Cannot use object of type WP_Error as array in /home/oakridge/deepredink/wp-content/plugins/elastic-email-sender/api/ElasticEmailClient.php on line 58`

**Comment by rkwasniewski** [comment]
Our service provider (OVH) is experiencing global news in their data centers that impact many companies, including Elastic Email. Thank you for patience and sorry for the inconvenience.
